// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';

part 'ai_report_models.freezed.dart';
part 'ai_report_models.g.dart';

/// Report period: weekly or monthly.
enum ReportPeriod {
  /// 7-day weekly report.
  @JsonValue('weekly')
  weekly,

  /// Calendar-month monthly report.
  @JsonValue('monthly')
  monthly,
}

/// Source of an [AiReportResponse] — LLM-generated or numeric preset fallback.
enum AiReportSource {
  /// Generated by the local LLM via n8n webhook.
  @JsonValue('llm')
  llm,

  /// Numeric preset fallback (LLM unavailable or parse failure).
  @JsonValue('preset')
  preset,
}

/// Aggregated metrics for the report period covering three intensity axes:
/// 작성 강도 (schedule authoring), 이행 강도 (execution), 체크 강도 (completion check).
@freezed
sealed class AiReportInputData with _$AiReportInputData {
  /// Creates an aggregated metrics payload.
  const factory AiReportInputData({
    // 이행 강도 (execution intensity)
    @JsonKey(name: 'focus_sessions') required int focusSessions,
    @JsonKey(name: 'avg_focus_ratio') required double avgFocusRatio,
    @JsonKey(name: 'planned_minutes') @Default(0) int plannedMinutes,
    @JsonKey(name: 'actual_focus_minutes') @Default(0) int actualFocusMinutes,
    @JsonKey(name: 'sessions_by_grade')
    @Default(<String, int>{})
    Map<String, int> sessionsByGrade,
    // 체크 강도 (completion intensity)
    @JsonKey(name: 'todos_total') @Default(0) int todosTotal,
    @JsonKey(name: 'todos_completed') @Default(0) int todosCompleted,
    @JsonKey(name: 'todos_completed_on_due_day')
    @Default(0)
    int todosCompletedOnDueDay,
    @JsonKey(name: 'non_todo_completed') @Default(0) int nonTodoCompleted,
    // legacy aliases retained for compatibility
    @JsonKey(name: 'tasks_completed') required int tasksCompleted,
    @JsonKey(name: 'tasks_total') required int tasksTotal,
    // 작성 강도 (authoring intensity)
    @JsonKey(name: 'schedules_created') @Default(0) int schedulesCreated,
    @JsonKey(name: 'schedules_total_minutes')
    @Default(0)
    int schedulesTotalMinutes,
    @JsonKey(name: 'category_distribution')
    @Default(<String, int>{})
    Map<String, int> categoryDistribution,
    // streak (carry-over)
    @JsonKey(name: 'streak_days') required int streakDays,
  }) = _AiReportInputData;

  /// Parses JSON (snake_case keys) into [AiReportInputData].
  factory AiReportInputData.fromJson(Map<String, dynamic> json) =>
      _$AiReportInputDataFromJson(json);
}

/// Request body sent to n8n `routinemon-ai-{weekly,monthly}-report` webhook.
@freezed
sealed class AiReportRequest with _$AiReportRequest {
  /// Creates a report request.
  const factory AiReportRequest({
    @JsonKey(name: 'user_id') required String userId,
    required ReportPeriod period,
    @JsonKey(name: 'period_start') required DateTime periodStart,
    @JsonKey(name: 'period_end') required DateTime periodEnd,
    required AiReportInputData data,
    @JsonKey(name: 'user_locale') required String userLocale,
  }) = _AiReportRequest;

  /// Parses JSON into [AiReportRequest].
  factory AiReportRequest.fromJson(Map<String, dynamic> json) =>
      _$AiReportRequestFromJson(json);
}

/// Structured report generated by the LLM (or preset fallback).
@freezed
sealed class AiReportResponse with _$AiReportResponse {
  /// Creates a report response.
  const factory AiReportResponse({
    required String summary,
    required List<String> insights,
    required List<String> suggestions,
    required String encouragement,
    required AiReportSource source,
  }) = _AiReportResponse;

  /// Parses JSON into [AiReportResponse].
  factory AiReportResponse.fromJson(Map<String, dynamic> json) =>
      _$AiReportResponseFromJson(json);
}
