// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.starwinde.routinemon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object DisturbanceApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is DisturbanceFlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class DisturbanceFlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()
private open class DisturbanceApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}

/**
 * Native disturbance API (T5.21 일정별 방해 허용).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface DisturbanceApi {
  /** Vibrate for [durationMs]. [amplitude] is 1..255 (-1 = default). */
  fun vibrate(durationMs: Long, amplitude: Long)
  /** Send the user to the home screen (Intent ACTION_MAIN/CATEGORY_HOME). */
  fun launchHome()
  /** Whether the routinemon DeviceAdminReceiver is currently active. */
  fun isDeviceAdminActive(): Boolean
  /** Launch the system intent to grant DEVICE_ADMIN to routinemon. */
  fun requestDeviceAdmin()
  /**
   * Lock the screen via DevicePolicyManager.lockNow().
   * No-op when DEVICE_ADMIN is not active.
   */
  fun lockDevice()
  /**
   * Start a lightweight foreground service so the process is not killed
   * while the disturbance schedule is active. Idempotent.
   */
  fun startDisturbanceService()
  /** Stop the disturbance foreground service. Idempotent. */
  fun stopDisturbanceService()
  /**
   * SYSTEM_ALERT_WINDOW (다른 앱 위에 표시) 권한 부여 여부.
   * L2/L3 launchHome BAL 우회에 필수.
   */
  fun isOverlayPermissionGranted(): Boolean
  /** "다른 앱 위에 표시" 시스템 설정 화면을 연다. */
  fun requestOverlayPermission()
  /** 배터리 최적화 제외 여부 (process 안정성 확보). */
  fun isBatteryOptimizationIgnored(): Boolean
  /** 배터리 최적화 제외 요청 시스템 설정을 연다. */
  fun requestBatteryOptimizationExemption()
  /** POST_NOTIFICATIONS 권한 부여 여부 (Android 13+). */
  fun isNotificationPermissionGranted(): Boolean
  /** 앱 알림 설정 화면을 연다. */
  fun openNotificationSettings()
  /**
   * L1 검은 풀스크린 오버레이 표시. SYSTEM_ALERT_WINDOW 권한 필수.
   * [durationMs] 후 자동 해제.
   */
  fun showBlackOverlay(durationMs: Long)
  /** L2 차단 다이얼로그 (반투명 중앙). [countdownSec] 후 자동 해제. */
  fun showBlockDialog(countdownSec: Long)
  /** L3 풀스크린 차단 오버레이. dismissOverlay 호출 전까지 유지. */
  fun showBlockFullscreen()
  /** 현재 표시된 disturbance 오버레이를 즉시 해제. */
  fun dismissOverlay()
  /**
   * 활성 일정 동안 시스템 알림 영역에 sticky 알림을 표시 — USB 연결
   * 알림과 동일한 패턴 (`setOngoing(true)` foreground service notification).
   * 사용자는 swipe 로 지울 수 없고 "모두 지우기" 도 무시. 일정 종료/변경
   * 시 [stopScheduleNotification] 또는 [updateScheduleNotification] 호출.
   * 동일 service 인스턴스는 idempotent — 이미 떠 있으면 콘텐츠만 갱신.
   */
  fun startScheduleNotification(title: String, subtitle: String)
  /**
   * 떠 있는 일정 알림의 텍스트만 갱신 (예: 남은 분 update).
   * 알림이 없으면 새로 시작 — start 와 동작 동일.
   */
  fun updateScheduleNotification(title: String, subtitle: String)
  /** 일정 알림 즉시 해제 — service stop. */
  fun stopScheduleNotification()

  companion object {
    /** The codec used by DisturbanceApi. */
    val codec: MessageCodec<Any?> by lazy {
      DisturbanceApiPigeonCodec()
    }
    /** Sets up an instance of `DisturbanceApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DisturbanceApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.vibrate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val durationMsArg = args[0] as Long
            val amplitudeArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.vibrate(durationMsArg, amplitudeArg)
              listOf(null)
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.launchHome$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.launchHome()
              listOf(null)
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.isDeviceAdminActive$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isDeviceAdminActive())
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.requestDeviceAdmin$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestDeviceAdmin()
              listOf(null)
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.lockDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.lockDevice()
              listOf(null)
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.startDisturbanceService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startDisturbanceService()
              listOf(null)
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.stopDisturbanceService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopDisturbanceService()
              listOf(null)
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.isOverlayPermissionGranted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isOverlayPermissionGranted())
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.requestOverlayPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestOverlayPermission()
              listOf(null)
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.isBatteryOptimizationIgnored$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isBatteryOptimizationIgnored())
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.requestBatteryOptimizationExemption$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestBatteryOptimizationExemption()
              listOf(null)
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.isNotificationPermissionGranted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isNotificationPermissionGranted())
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.openNotificationSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openNotificationSettings()
              listOf(null)
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.showBlackOverlay$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val durationMsArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.showBlackOverlay(durationMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.showBlockDialog$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val countdownSecArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.showBlockDialog(countdownSecArg)
              listOf(null)
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.showBlockFullscreen$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.showBlockFullscreen()
              listOf(null)
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.dismissOverlay$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.dismissOverlay()
              listOf(null)
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.startScheduleNotification$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val titleArg = args[0] as String
            val subtitleArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.startScheduleNotification(titleArg, subtitleArg)
              listOf(null)
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.updateScheduleNotification$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val titleArg = args[0] as String
            val subtitleArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.updateScheduleNotification(titleArg, subtitleArg)
              listOf(null)
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.routinemon.DisturbanceApi.stopScheduleNotification$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopScheduleNotification()
              listOf(null)
            } catch (exception: Throwable) {
              DisturbanceApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
